title: تحریر
description: تفالی بر غزل حافظ
author: bonyad
language: Farsi

url: https://bonyad.github.io/tahrir/
root: /tahrir/

done: ۱۰

default_extension: md

permalink: ghazal/:title/

post_num: all
archive_post_num: all
post_sort: reverse

lists:
  - list
  - alphabet

template: tahrir
